(defparameter balance 100)

(defun withdraw (amount)
    (if (>= balance amount)
        (progn (setf balance (- balance amount))
               balance)
        "Insufficient funds"))

(defun new-withdraw ()
    (let ((balance 100))
        (lambda (amount)
            (if (>= balance amount)
                (progn (setf balance (- balance amount))
                       balance)
                "Insufficient funds"))))

(defun make-withdraw (balance)
    (lambda (amount)
        (if (>= balance amount)
            (progn (setf balance (- balance amount))
                   balance)
            "Insufficient funds")))

(defun make-account (balance)
    (let ((current-balance balance))
        (lambda (m)
            (cond ((eq m 'withdraw)
                      (lambda (amount)
                          (if (>= current-balance amount)
                              (setf current-balance (- current-balance amount))
                              "Insufficient funds")))
                  ((eq m 'deposit)
                      (lambda (amount)
                          (setf current-balance (+ current-balance amount))
                          current-balance))
                  (t (error "Unknown request: MAKE_ACCOUNT ~A" m))))))

(defparameter acc (make-account 100))