;; Serializing
; Serialization creates distinguished set of procedures such that only one execution of a procedure in each serialized set is permitted to happen at a time.
; (parallel-execute ⟨p_1⟩ ⟨p_2⟩... ⟨p_k⟩)

(defun make-account (balance)
    (labels ((withdraw (amount)
                       (if (>= balance amount)
                           (progn (setf balance (- balance amount))
                                  balance)
                           "Insufficient funds"))
             (deposit (amount)
                      (setf balance (+ balance amount))
                      balance))
      (let ((protected (make-serializer)))
        (labels ((dispatch (m)
                   (cond ((eq m 'withdraw) (funcall protected #'withdraw))
                         ((eq m 'deposit) (funcall protected #'deposit))
                         ((eq m 'balance) balance)
                         (t (error "Unknown request: MAKE-ACCOUNT ~A" m)))))
          #'dispatch))))

; `deposit` message accepts negative amounts!
(defun exchange (account1 account2)
    (let ((difference (- (funcall account1 'balance)
                         (funcall account2 'balance))))
        (funcall (funcall account1 'withdraw) difference)
        (funcall (funcall account2 'deposit) difference)))

(defun make-account-and-serializer (balance)
    (labels ((withdraw (amount)
                       (if (>= balance amount)
                           (progn (setf balance (- balance amount))
                                  balance)
                           "Insufficient funds"))
             (deposit (amount)
                      (setf balance (+ balance amount))
                      balance))
        (let ((balance-serializer (make-serializer)))
            (labels ((dispatch (m)
                      (cond ((eq m 'withdraw) (funcall (funcall balance-serializer #'withdraw)))
                            ((eq m 'deposit) (funcall (funcall balance-serializer #'deposit)))
                            ((eq m 'balance) balance)
                            ((eq m 'serializer) balance-serializer)
                            (t (error "Unknown request: MAKE-ACCOUNT ~A" m)))))
        #'dispatch))))

(defun deposit (account amount)
    (let ((s (funcall account 'serializer))
          (d (funcall account 'deposit)))
        (funcall (funcall s d) amount)))

(defun serialized-exchange (account1 account2)
    (let ((serializer1 (funcall account1 'serializer))
          (serializer2 (funcall account2 'serializer)))
        (funcall (funcall serializer1 (funcall serializer2 #'exchange))
                 account1
                 account2)))

(defun make-serializer ()
    (let ((mutex (make-mutex)))
        (lambda (p)
            (let ((serialized-p (lambda (&rest args)
                                  (funcall mutex 'acquire)
                                  (let ((val (apply p args)))
                                    (funcall mutex 'release)
                                    val))))
              serialized-p))))

(defun make-mutex ()
    (let ((cell (list nil)))
        (labels ((the-mutex (m)
                            (cond ((eq m 'acquire)
                                      (if (n-test-and-set cell)
                                          (the-mutex 'acquire)))
                                  ((eq m 'release) (n-clear cell)))))
          #'the-mutex)))

(defun n-clear (cell) (rplaca cell nil))

(defun n-test-and-set (cell)
    (if (car cell) t (progn (rplaca cell t) nil)))