(defun add-poly (p1 p2)
    (if (same-variable-p (variable p1) (variable p2))
        (make-poly (variable p1)
                   (add-terms (term-list p1) (term-list p2)))
        (error "Polys not in same var: ADD-POLY ~A" (list p1 p2))))

(defun mul-poly (p1 p2)
    (if (same-variable-p (variable p1) (variable p2))
        (make-poly (variable p1)
                   (mul-terms (term-list p1) (term-list p2)))
        (error "Polys not in same var: MUL-POLY ~A" (list p1 p2))))